# Generated by Django 5.2.4 on 2025-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_established', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('impacted_sectors', models.TextField()),
                ('most_impacted_sector', models.TextField()),
                ('pdf_file', models.FileField(upload_to='policies/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
