# Generated by Django 5.2.4 on 2025-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyanalysis',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
